### ISSUE TITLE
Wine without Proot

### ISSUE THREAD

**Issue by IntinteDAO** [Boxvidra/Boxvidra-Android#5]
In TUR repository you have Hangover Wine, that's a Wine with box64. In theory it should be better than Prooting distro etc. (faster).

**Comment by xoureldeen** [comment]
> In TUR repository you have Hangover Wine, that's a Wine with box64. In theory it should be better than Prooting distro etc. (faster).

im not ready for this headache, i did and faced alot of bugs (same reason why cassia canceled)

my main target is desktop environment with full experience.
