### ISSUE TITLE
Command failed with exit code 1

### ISSUE THREAD

**Issue by PrintHelloPeople** [Boxvidra/Boxvidra-Android#6]
Hi, I get this error after I select the OBB file:
Error:
/system/bin/sh: <stdin>[1]: syntax error: unexpected '('
Error: Command failed with exit code: 1

![Screenshot_20240723-123513](https://github.com/user-attachments/assets/7b66c063-9d22-40a6-85aa-58c9d8c5212b)

I'm using latest apk version 1.1 and latest OBB
My phone is a Motorola Moto g34

Thx for your fantastic project

**Comment by PrintHelloPeople** [comment]
This error was caused by the obb file name that included a (). Fixed by removing ()

**Comment by xoureldeen** [comment]
> Hi, I get this error after I select the OBB file:
> Error:
> /system/bin/sh: <stdin>[1]: syntax error: unexpected '('
> Error: Command failed with exit code: 1
> 
> ![Screenshot_20240723-123513](https://github.com/user-attachments/assets/7b66c063-9d22-40a6-85aa-58c9d8c5212b)
> 
> I'm using latest apk version 1.1 and latest OBB
> My phone is a Motorola Moto g34
> 
> Thx for your fantastic project

Check file path
